In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_confirmed = pd.read_csv('confirmed_covid_cases.csv')

In [4]:
df_confirmed

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,3/1/23,3/2/23,3/3/23,3/4/23,3/5/23,3/6/23,3/7/23,3/8/23,3/9/23,Total
0,0,0,0,0,0,0,0,0,0,0,...,209340,209358,209362,209369,209390,209406,209436,209451,209451,389965407
1,0,0,0,0,0,0,0,0,0,0,...,334408,334408,334427,334427,334427,334427,334427,334443,334457,556687962
2,0,0,0,0,0,0,0,0,0,0,...,271448,271463,271469,271469,271477,271477,271490,271494,271496,548224950
3,0,0,0,0,0,0,0,0,0,0,...,47875,47875,47875,47875,47875,47875,47875,47890,47890,73642575
4,0,0,0,0,0,0,0,0,0,0,...,105277,105277,105277,105277,105277,105277,105277,105288,105288,180075609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,0,0,0,0,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,1237631088
285,0,0,0,0,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,643386
286,0,0,0,0,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,23638305
287,0,0,0,0,0,0,0,0,0,0,...,343012,343079,343079,343079,343135,343135,343135,343135,343135,587861049
288,0,0,0,0,0,0,0,0,0,0,...,264127,264127,264127,264127,264127,264127,264127,264276,264276,421155858

In [5]:
df_confirmed.isna().sum()

1/22/20    0
1/23/20    0
1/24/20    0
1/25/20    0
1/26/20    0
          ..
3/6/23     0
3/7/23     0
3/8/23     0
3/9/23     0
Total      0
Length: 1144, dtype: int64

### kết hợp với numpy

In [7]:
lst_total = np.array(df_confirmed['Total'])

In [8]:
lst_total

array([   389965407,    556687962,    548224950,     73642575,
          180075609,        14883,     12930765,  16876448763,
          856473969,    204007560,   3705294093,    100184874,
         1673517492,    759673704,    245990598,   2783088756,
         1054837566,   6631372902,   1480639983,     64506435,
         1071920049,   3928103043,    118945470,   1780953291,
         6841492947,    102524781,     50710320,     66989385,
         1817137812,    742719570,    513467964,  63548071782,
          240805236,   2050834308,     43656969,   1124004750,
           69447327,    112611267,    238248507,    250102644,
         1020374424,    650011722,           96,        42399,
          244125021,     90084174,     59134452,     14368593,
          137723283,      4873203,   2354063529,     52597350,
         1913669196,        32604,    237661317,      6285582,
           31028334,     15615990,   7058609262,      3946215,
           15893955,      6085866,      8746686,      1780917,
           39555660,      5125695,      1318311,      6506409,
            4612776,      7349202,      8859780,   1989989634,
          230877678,      5392257,      5762673,      5418537,
            4103085,     43266477,      3315678,      1331721,
             580542,       387105,      6468081,      5930940,
           67356372,      2974467,      8997609,      3697242,
             875751,    967837560,      3593637,      5791560,
            8691198,  12644487345,     15387609,     48447888,
          170399598,   1731357771,    174123297,   1943119935,
         1878580611,    761421018,   7317442893,     44087475,
           15498402,   4325373759,      2388060,     35489805,
           19881204,   1199891874,   1752451143,   1003802619,
          340701174,     34344522,     18706206,    873018762,
          128941947,    963760065,    110383311,   1587165363,
          150969429,    127573836,    249708750,    263815260,
           72933015,     87275691,    567132861,      7425648,
            3483690,     17374329,      2366613,  46767676536,
           94704075,     25276812,   2696194053,  41058131160,
          353345559,   5894048898,     24429828,   1736101293,
           81245109,     17368074,    112231521,     66512478,
              80421,    908012049,   3428736153,    247077864,
        87393359082,  11077220094,  13837267347,   4827229386,
         2403233886,   6665908062,  30249485034,    247797513,
        22014634893,   2973691158,   2594856999,    663947508,
            4189620,          900,  25403666904,    458075460,
         1239659340,    438105225,    276739965,   1236043008,
         2087296797,     59984022,     15074577,    926546268,
           26913480,   1824810564,    425019939,        28995,
          132430467,    163999158,   7122525234,    298576548,
           57795918,    167910549,      9405423,    111923406,
          314969811,  11832324042,     12219534,   1028027277,
           20161650,   1463150079,    460076262,   2408866830,
          410656416,    314333790,      3554736,   1960610712,
           66138759,     14813430,     69960996,     17143560,
        12161533653,      6302901,       208134,   1762839492,
           30333831,     18941889,    564900372,    607195146,
         1940672823,    820384347,   3239317485,      6222789,
         1675403427,     74988003,   1303585647,   7498239054,
         6844910631,  10931040072,   7217220126,    847178874,
         5282613576,  31735709526,    233107455,      8943390,
           41951973,     14582625,     14895699,     30556458,
           11259834,   1728723216,    179001360,   3688904040,
           72810627,     16984668,   2170648602,   4063233117,
         1713901608,     23310624,     53592039,   7839298467,
           35904354,  21213825444,   1183072497,    128810943,
            1496064,    132846852,   4413042186,   5738941353,
          105627651,   5899140780,     45807783,     57521001,
         6286974552,     40257663,     68196657,     14925684,
          250915698,   1933221849,  26522228097,       968703,
       161439553218,    310763778,   9571841550,   1960662375,
            4753608,     23882646,     10327485,     35915199,
                  0,      1814490,     29779452,     36631182,
           48724611,     77527938,      1243386,         2796,
            1061577,     10963299,  36072187368,   1496772240,
          480425223,     11347893,   1023537087,  12943774110,
         1237631088,       643386,     23638305,    587861049,
          421155858], dtype=int64)